### ISSUE TITLE
Some Nomads units registering as not having a class in class view

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/spooky-db#92]
![](https://i.imgur.com/3LNMCha.png)
See image.
All 3 units are standard and should belong in their factions counterparts class.

**Comment by spooky** [comment]
Will update, thanks for the report ;)

**Comment by spooky** [comment]
Seems that this is caused by the .bp values which, in HEAD of nomads develop branch is already fixed, so, I'll just update the index manually and hope that the next nomads release won't break this :P

**Comment by spooky** [comment]
updated
